
name = "workout-calculator"
main = "src/index.ts"
compatibility_date = "2023-01-01"

compatibility_flags = ["nodejs_compat"] # Example: If you need Node.js compatibility features

[[d1_databases]]
binding = "DB"
database_name = "workout-db"
database_id = "local-workout-db"
