
name = "workout-calculator"
main = "src/index.ts"
account_id = "316eeeb46903989490edaf0f69637963"
compatibility_date = "2023-01-01"

compatibility_flags = ["nodejs_compat"] # Example: If you need Node.js compatibility features

[[d1_databases]]
binding = "DB"
database_name = "workout-db"
database_id = "3a53e3e5-c967-4033-8d99-88cf3fff907d"
